### ISSUE TITLE
Re-fetch Season seems  to do nothing

### ISSUE THREAD

**Issue by LorenzoGarbanzo** [dularion/streama#140]

**Comment by dularion** [comment]
it actually works like this: 
if you got a season of a currently-running show, and themoviedb only has half of the season when you fetch it the first time, refetching it will fetch all the new episodes that were added since last time. And this behaviour works for me. Doesnt it for you?

**Comment by jsniemela** [comment]
Hey,

It does seem to work that way. I thought it would also re-fetch episodes that have been deleted from a season. Would that be a good addition? It might be a good idea to give some kind of a notification if the re-fetch is successful or not. Also it would be nice if it could automatically notify if there are new episodes available before the user clicks anything.

**Comment by dularion** [comment]
I agree that the refetch should update episodes, too. I was a bit iffy about that at first because that might override custom episode data, but I think I can find a way around that somehow. But exactly how do you mean refetch deleted episodes? You have manually deleted some episode from a season and refetch won't add it again? I would expect that to work, so if it doesn't I'll look into it. 
I like your ideas for notifications and will implement them :)

**Comment by jsniemela** [comment]
Yeah, that's what I meant. The only ways to add a deleted episode back into a season seems to be to delete the whole season and add it again or to add the episode manually. At first I thought this was what re-fetch was meant for.

**Comment by dularion** [comment]
I guess in the method where I check which episodes need to be fetched and which ones already are there I don't check for the deleted flag. Should be an easy fix. I'll look into it soon
