### ISSUE TITLE
Link support to external files (accessible via http, such as googledrive)

### ISSUE THREAD

**Issue by dularion** [dularion/streama#15]
Instead of having to upload everything, why not be able to add a linked file? Then the server is not the one taking care of delivering the video-content, it just plays it.

**Comment by kapilratnani** [comment]
I tried with symbolic links. Its working for me. 
It was tedious waiting for files to upload, even though the files are in same filesystem.

**Comment by ChristianGaertner** [comment]
then you could just store the absolute path to the file instead

**Comment by admwx7** [comment]
My server is running btrfs raid with multiple drives on it that's just aliased through the OS to a folder, haven't installed yet but my plan is to just reference that folder as if it was all local to begin with, this can also be handled for remote devices, at least in linux, as you can alias a remote storage device as a folder.

**Comment by dularion** [comment]
I think what you are describing overlaps with another issue, too: https://github.com/dularion/streama/issues/16
These two are getting mixed up a bit, what this issue was originally in reference to was linking to files via url, such as a file on googledrive.

**Comment by admwx7** [comment]
Googledrive might be a bad example since you can just link it to a folder on your OS using gsync.  An external FTP might be a better reference, but again you can alias that as a folder in Linux.  The only use case I can think of that you wouldn't be able to directly link or alias would be another streaming website.

**Comment by dularion** [comment]
yea, well.. this issue stems from a comment on reddit where a user asked for exactly that: linking in an external file via url, such as the ones he has on google drive. But I didn't make that very clear in the title... :P

**Comment by dularion** [comment]
for files on a drive without automatic crawling, I was going to program a file-browser. So the user can set another directory in the settings, which can then be used to browser files and folders in the application gui and select files from there. But maybe that is a stupid approach?

**Comment by admwx7** [comment]
I'm a fan of auto crawlers that will populate your media given a parent folder, however that's a lot of work and would essentially branch off of a file-browser to begin with, so that seems like a reasonable approach to me.

HTTP based linking is a security risk, if they aren't comfortable enough with the media to link it through their server or another device on their network then how could it be trusted to stream through streama?

**Comment by majorcyto** [comment]
Hi,
Any progress at looking at linking to video files in CDN's or Drives. (Amazon, Google Drive, MediaFire, Anything with a direct link to the file lol)

**Comment by Jeronimo95** [comment]
Is there any issue with using the "External File" feature to do this? You should be able to link any file on those services.

**Comment by ArchieGu** [comment]
Will a local shareable link be supported (minIO) ?
It looks like this :
`http://127.0.0.1:9000/videobuck/Galapagos.EP01.Born.of.Fire.2006.1080p.BluRay.x264-WiKi.chs%26eng.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PLZMNVMP4TM518QYFJZ9%2F20190529%2F%2Fs3%2Faws4_request&X-Amz-Date=20190529T023255Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=668463a08b2eaefdf13c0b47480522d823c112a79793b77680a2632cfa454612`

I tried to put the link in external url, it gave me error.
