### ISSUE TITLE
Any way of adding ads before and/or during play?

### ISSUE THREAD

**Issue by vaMuchenje** [dularion/streama#159]

**Comment by dularion** [comment]
Not currently, no. Video ads you mean? For monetization purposes?

**Comment by gkiko** [comment]
No ads please

**Comment by vaMuchenje** [comment]
@dularion yes. I am using streama to build a site for indie series creators in my home country. If i could find a way to at have them earn something from their content, it would be nice. Right now, even Youtube has no monetization for the country.

**Comment by dularion** [comment]
Ok that makes sense. But would you then need a system where views of the ads are tracked and counted somehow? And would you need different ads per content manager so that each can manage their own ads? And would they be displayed at random or do you need to decide which video gets which ad? And is an ad before playback enough or do you need to interrupt longer videos for ads as well? Basically: describe exactly what you need and I'll see what I can do. 

@gkiko, of course this is optional, so if no ads are configured the application would be ad free

**Comment by strayedsoul2003** [comment]
So basically this guy wants to take your project that you kindly have put out there, and make money off your work... Humm there is a word for that.. Freeloader.. Should just tell him if he wants ads the source code is there, learn programming and do it himself.. Stay pure to the concept of this being for PERSONAL / Free use.

**Comment by Jeronimo95** [comment]
I'm going to close this because I don't think streama should be the one adding the advertising system. If people want to use streama as a base for something like that they can.
