### ISSUE TITLE
embed video (request)

### ISSUE THREAD

**Issue by csong95** [dularion/streama#369]
I was wondering since there site like mp4upload, stream.moe, openload, vidstream, video streaming hosting site etc why not allow these site to be able to embed into the video player like some custom video player do with youtube,vimeo,facebook etc since it would be less costly on bandwith and storage.

**Comment by dularion** [comment]
you mean that you want to point to an external video file from within streama? That is already possible through the **External URL** feature. Or do you have something else in mind?
![image](https://cloud.githubusercontent.com/assets/936076/25682085/1451ad68-3057-11e7-8aad-6444afd291a9.png)

**Comment by csong95** [comment]
So you can't use the external url with video streaming site since there only allowing embed player from there site. But what i know it External url only work with video file that are direct links to the mp4 file. Do you think there a way to modify the html5 video player to allow this video sites to play the video in the streama player? I hope i'm not confusing you .

**Comment by majorcyto** [comment]
Hi,

For sites like OpenLoad and MP4Upload (These two sites are used the most) they require that you use their embedded video player because it plays ads in the video player, in exchange you get to host the video for free/unlimited with them.

If you could add a third option that would accept a HTML embed code for their video player or something of that sort that would work great! Here is an embed example of a video I have in my MP4 Upload account:

`<IFRAME SRC="https://www.mp4upload.com/embed-76gtlrahpmt1.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=1920 HEIGHT=1080 allowfullscreen></IFRAME>`

**Comment by majorcyto** [comment]
Sometimes, It is possible to play the file from within your custom video player directly but you would have to write a script to basically..

1. Generate a link request to the remote host (MP4 Upload)
2. Grab the actual CDN Edge Server video link
3. Use that as the SRC to play the video File

Then that link will eventually expire, which is why it would have to generate a request each time the user clicks on that episode/video. It is quite a bit work, the same method is used above to pull a video straight from the Edge CDN server for Google Drive videos instead of actually embedding from Google Drive (which has limits) a-la something like this: http://api.getlinkdrive.com/

But again this is a lot more work, and it would most likely be easier to find a way to just allow a HTML player embed instead.

**Comment by csong95** [comment]
This look like it would be easy achieve with https://openload.co since they have a api.
