### ISSUE TITLE
Squandering an opportunity

### ISSUE THREAD

**Issue by untotren** [dularion/streama#406]
It is sad I had great hopes for this project but it seems you are letting it die.  I was hoping this could be a great alternative to Emby/Plex @dularion

**Comment by dularion** [comment]
Well I'm glad you had hopes, unfortunately I'm 99% maintaining this project by myself, and I'm a mom of a toddler, went through a move from one country to another this past year and am a part owner of a software engineering company where I'm putting in overtime constantly. Also I've been sick a lot these past months and was on vacation without internet access. If you have any suggestions how I could better manage my time, be my guest, but until then I'd appreciate some sympathy and understanding. I'm doing my best to test all releases fully and also all PRs because if things break in a release I have to respond quickly, at the same time I wanna accept the few PRs that this project gets swiftl, so as to not squash the motivation of the devs. Don't know what to tell ya mate, either help me out or wait till there's another alternative out there, or just stick around - slow and steady may win the race

**Comment by untotren** [comment]
Could you set up a patreon?  Perhaps people like me could donate to the cause and alleviate some of the need for overtime.

**Comment by Jeronimo95** [comment]
@untotren I've started maintaining a [fork](https://github.com/Jeronimo95/streama/). Goals are to be a great & truly open source alternative to Emby/Plex.

**Comment by sfunk1x** [comment]
@dularion I've been watching this project for a while now, and definitely appreciate the efforts here. I would be elated to completely replace Plex in my home setup.

I think a Patreon account (or some way to donate) is a great idea. Also, would it be possible to allow other contributors some administrative control of the repo to handle PRs and the like (or setups another 'group' repo)? That might remove some of the project maintenance burden from you and assist in stoking development efforts, as long as there is a clear understanding of project roadmap. Something this large has to be a group effort if it's going to survive long term, and it's clear we do need it to survive and improve.

**Comment by dularion** [comment]
Certainly! I'm welcoming any willing Co maintainers on board, only requirement is that they have made at least one PR so that I can check what they are capable of

**Comment by dularion** [comment]
also, patreon sounds great!
