### ISSUE TITLE
Android - can't scroll on dashboard

### ISSUE THREAD

**Issue by dularion** [dularion/streama#495]
### Issue description
its been reported by multiple ppl: scrolling in dashboard seems to be broken for some devices. anyone who can add more info to this issue is very welcome, like Device, android version, etc

**Comment by videojock** [comment]
HTC M8 Phone - Android 6 Build 6.12 with HTC Sense ver7'00

**Comment by videojock** [comment]
Google Nexus 8" Tablet Android ver 6.01

**Comment by videojock** [comment]
Previous Streama apk did scroll on this hardware and Android ver 6.00 but had other issues which have been documented

**Comment by dularion** [comment]
seems like v1.4.1 RC3 fixes the issue of tv-shows, movies and generic Videos not loading. have a look. 
If this is  not what is meant by "can't scroll", then please let me know!

**Comment by videojock** [comment]
Not fixed with RC3, still not showing TV Shows, Movies or Generic Videos only 'Continue Watching' also Search doesn't work., This is the same on both mobile and tablet with Android Ver 6.00 and 6.01

**Comment by dularion** [comment]
Hi, I just released a new version for the app. Please check if its fixed there!

**Comment by videojock** [comment]
Hi, the app is now displaying but only 30 in each section. The search is now working.
The worst problem I have is that the videos now load very slowly on the normal web browser and I cannot upload videos, they just race past on the uploading and never process because no file has been uploaded. 
I have tried to go back to last version to correct this problem, now I have the same trouble with that version, so something has happened in the data base  which is H2 not SQL, or something else.
Not a very happy bunny at the moment as I have a lot of content uploaded which has been working flawlessly on the Windows platform.
I am not sure if you are aware that on the Windows platform a directory is create -C:/users/name of user/appdata/local/temp/2/ In this directory videos are duplicated with other settings. These videos need to be deleted after a while or the C: drive becomes full. I have attached the contents of the directory 2.
[folder 2.txt](https://github.com/dularion/streama/files/1574718/folder.2.txt)

**Comment by videojock** [comment]
Hi 
I think I may have something strange going on with regard to the uploading etc in the Chrome browser and the PC. I am digging deeper to find out

**Comment by dularion** [comment]
> Hi, the app is now displaying but only 30 in each section.  
this is kinda wanted behaviour. the only thing missing is the load-more. I can implement that fore mobile tho

**Comment by dularion** [comment]
> Not a very happy bunny at the moment as I have a lot of content uploaded which has been working flawlessly on the Windows platform.

well damn. thats ofc not good. however, I actually didnt really mess around with the data in general. So i cant really see the connection, especially if you reverted back to an old version everything should be the same. 

if you wanted you could give me access to a throwaway account on your system and I could check it out. if so, hit me up on gitter.

> I am not sure if you are aware that on the Windows platform a directory is create -C:/users/name of user/appdata/local/temp/2/

Yea, my brother started coding on streama recently and then we noticed this too. tbh, these kinds of systems, like java applications with a web frontend etc, are usually not so well suited for windows. I mean, for development, sure. But as soon as you are talking about real hosting, then i would go with a virtual server somewhere like amazon servers or digital ocean or, for more control, an old tower PC with ubuntu installed. Windows tends to be kinda weird when it comes to a lot of hosting stuff, which is why it is commonly avoided for that task.   

Lastly, if you are using the app so much as your message indicates, please consider migrating your data over to mysql. With mysql you can more easily backup, recover and adjust your data. H2 is more of a temporary "getting-started" type of thing.
