### ISSUE TITLE
Add support for the latest gradle (4.x)

### ISSUE THREAD

**Issue by ridhwaans** [dularion/streama#565]
Running streama on gradle 4.5 never works. Tried bootRun and it returns a mainclass exception "Illegal null value provided in this collection: [null]". I had to revert to Gradle 3.5.1 for streama to work.

Asking a fix for that

**Comment by dularion** [comment]
Thats unfortunately nothing thing can happen any time soon, because we use a certain version of grails, and that version of grails supports a certain version of gradle. Once we do a major grails update again, I'm sure the newer version for gradle will automatically work. In the mean time, I'd suggest not caring about the gradle version at all. Just use the built-in gradle wrapper. One example command is `./gradlew assemble`
