### ISSUE TITLE
Port to Unity?

### ISSUE THREAD

**Issue by admwx7** [dularion/streama#64]
I think we've come to the point where a list would do good, I'll update this as we discuss.

Unity over Angular benefits:
- Support for outlier cases of users (console/TV users that don't want to use a remote)

Angular over Unity:
- Same language for front/back-end
- Potential to run the same code for front/back-end
- Significantly more experience in the community
- No need to install apps on all your devices (though I found a section about web pages built with unit so maybe not?)
- No large learning curve
- Won't have to support a controller navigation layout - games take months to port controls between console and PC and still sometimes screw it up, think the Plex desktop app here, you can't even use your mouse!

**Comment by admwx7** [comment]
@dantheman213 I would of linked you directly to the full specs and told you the section, however they require you to be a memeber of the DLNA community to view it so I couldn't.  However, if you don't believe me, give emby a try, switched over from Plex ~ 3 months ago, relatively painless and doesn't require you to kill your plex server even!  You can use their "Select a Player" section to select DLNA devices to play directly to, as it's describe in the Wiki page I linked earlier.

**Comment by dantheman213** [comment]
@admwx7 I'll check it out. Based on past experiences with DLNA though I don't have high hopes unless there's more going on with their service than just the DLNA protocol.

**Comment by admwx7** [comment]
They key is that you just turn your DLNA device on and make sure it's got DLNA turned on with a valid video player installed (in the case of xbone).  Pretty much if your console can search the server for media then it should be able to get media pushed to it through the DLNA protocol.  After that you just use the web interface or your mobile app to do all the controlling, which I'm not a fan of using a controller for navigation to begin with so it's preferable for me.

**Comment by Copytalky** [comment]
@dantheman213 I believe what admwx7 was trying to portray before (correct me if I'm wrong), is that DLNA on the PS3/PS4 has no fancy interface, it is a file folder structure interface, however if you utilize the 'emby' app on your phone, and your PS3/PS4 is turned on and talking on your LAN, the DLNA media server (emby) will see the PS3/PS4 device, and on your mobile you can browse through the emby app all of your shows in the nice UI that you've wanted. Then when you find a show, you tell Emby to send the show to your PS3/PS4, the PS3/PS4 is listening on the network and gets the request from your Emby server on the LAN and starts streaming the show.

with @admwx7 last comment, it all clicked with what he was trying to explain before - seeing as I'm not as well versed with DLNA - I thought DLNA was rather a one way protocol in the sense that your PS3/PS4 can go onto a LAN and find a DLNA server like emby/plex/windows, and browse through the folders for your media, I didn't realize it has the capability of sending out requests from a DLNA server to devices and force them to stream content you've sent to that device via other devices aka mobile/PC.

For some people that may work just fine, they may rather use their mobile/tablet/PC to choose shows then send them to the PS3/PS4 etc. What @dantheman213 and some others want is a platform that scales it's UI across all devices. that one UI that's compatible across all devices can still have DLNA features.

I will say that both options are great, @dantheman213 approach is going to be far more complicated/less coders out there that are willing to contribute, but has the biggest payoffs potentially.

I'm not a great coder myself, I don't understand all the frameworks/libraries/platforms etc. and their best use cases, but I had figured from researching so much into react/flux(soon to be relay) and immutableJS along with webkit(rather utilize the gibbon netflix approach) and of course nodejs, would create the ultimate JS based multi platform scalable system with the largest developer base available out there in the open-source community.

Everyone's entitled to their opinions, we have a lot of great options that have been presented and I don't necessarily see any options laid out that have full on road-blocks for cross platform scaling. What I do see is the idea being forked and people going their own ways due to not agreeing with technologies chosen for this project (which is ok!), it's not ideal to have people split off instead of contributing to one project, but to each their own.

I'm a little worried personally about unity just because i'm not familiar at all with it, not a c#/.net programmer, nor have a lot of experience with the MVC model. I don't doubt that unity can complete this project - it's just how much work is it going to take to build? What is available in the unity world so that the project doesn't have to have every aspect built from scratch? is there a webkit/cordova style alternative SDK that will eliminate the need for a platform engine app to be built across all of these devices? etc.

If the building blocks are available in the unity world just like the building blocks are available in the JS world, then I see unity as a learning curve that developers will need to adapt to if they want to contribute to this project. But if tons of stuff has to be built for unity that already exists in the JS world, then  I see it has a detriment to the progress timeline of the project.

**Comment by dantheman213** [comment]
I actually created a repo to pursue this idea. Check out the other ticket at the bottom for more info..
https://github.com/dularion/streama/issues/20#issuecomment-127828295

**Comment by admwx7** [comment]
https://github.com/dantheman213/ambrosia

If you want to get in on the action
