### ISSUE TITLE
Smart Phone App

### ISSUE THREAD

**Issue by alallier** [dularion/streama#70]
Having smartphone apps for Android, iOS, etc. for streama, I think would be a great feature.

**Comment by dularion** [comment]
I agree! But I've been struggling a bit with this. How would we get this to work with a self-hosted application? Would you on login to the app choose the url to the running self-hosted version of streama?

**Comment by alallier** [comment]
Yes I would think so, same idea as going to the url in your web browser, at the initial start of the app they would configure their url. Or somehow utilize the invite email, so that if they opened the email on their phone it would open the app and auto fill

**Comment by dcampogiani** [comment]
Is there any documentation on REST API? I'd like to start working on a proof of concept android client this weekend if I have some free time.

**Comment by admwx7** [comment]
So is Cordova off the table at this point?

**Comment by dularion** [comment]
Cordova is NOT off the table, why would it be? It is awesome! 
@dcampogiani, no documentation, this file is sort a list of endpoints & methods: https://github.com/dularion/streama/blob/master/grails-app/assets/javascripts/services/api-service.js

**Comment by admwx7** [comment]
Just asking since we have someone starting work on a native app, doesn't
make sense to have both, time would be better spent in one or the other IMO.

**Comment by dularion** [comment]
ah, you mean like that. You are of course right...  @dcampogiani, you are going to program natively? I personally prefer a cordova-approach, simply because everything is REST anyway, so it sort of makes sense to go for one-size-fits-all with web-technology (ie cordova). On the other hand, if @dcampogiani is willing to put his personal time into it, I sort of believe he should do what he is most comfortable with. But if you are just as comfortable with a cordova-style app, we should definitely talk about it imo!

**Comment by admwx7** [comment]
I'm in favor of cordova since it means we don't have to find someone
interested in iOS and someone in Windows mobile *cringe* on top of
Android.  Plus it keeps the stack clean, one language to rule them all.
And I know we have at least a few bootstrap pros hiding around here,
cordova rendering a pretty app on mobile is really just finding some people
that can do mobile friendly sites really well.  Now it takes actually
knowing some of the working in cordova to get support for native features,
but those can be learned.

**Comment by dularion** [comment]
Actually, I find [ionic](http://ionicframework.com/) + [ngcordova]( http://ngcordova.com/) to be the most reliable mix for any hybrid mobile development.

**Comment by admwx7** [comment]
I'll have to check it out then, looks like it adds some nice features.

**Comment by dcampogiani** [comment]
In the past I wrote something using Cordova + Angular (and Ionic) but I prefer the native approach. Tomorrow I'll start holidays and I hope to find some free time to play with streama API.

**Comment by dcampogiani** [comment]
I'm starting understanding the REST API and I have some questions.

- If I try to GET */tvShow.json* without being previously logged I still get a 200 OK, with a form in the body. I think a 401 would be better.
- If I first "login", doing a POST at */j_spring_security_check* with field *j_username* and *j_password* then the GET at */tvShow.json* it's working.

I think the each REST API should be self-contained with all field required (such as authentication) in the request. I've used spring security only once in the past and in that project we used the spring support for HTTP BASIC.

**Comment by dularion** [comment]
Yea, well I have yet to figure out how to get spring security nicely working with REST. it tends to always do a redirect, which i find very very bad. I fonud this now, which seems promising: https://grails.org/plugin/spring-security-rest

**Comment by dularion** [comment]
http://alvarosanchez.github.io/grails-spring-security-rest/1.5.1/docs/guide/introduction.html

**Comment by dularion** [comment]
Ok so  I learned something yesterday. Apparently Chromecast only works for native apps currently. There is a Cordova plug in but it doesn't seem like it is being developed right now.  And for me that means that I will develop a native app (first ios, then android) that functions as a Chromecast remote. But don't let me stop you guys and your work! Just letting you know what my plan is. I will add links to the repositories here soon!

**Comment by lupoalberto12** [comment]
Are there some news for it?
I think an app (and Chromecast support) can be a must!
Bye!

**Comment by dularion** [comment]
First app release is out, but this is still alpha status. anyone who wants to be invited to the closed beta later let me know with your email addr

**Comment by dularion** [comment]
https://github.com/dularion/streama-app/releases/tag/v0.0.1
