### ISSUE TITLE
TV Show Episode Files Upload

### ISSUE THREAD

**Issue by alallier** [dularion/streama#73]
When I select fetch all episodes for season and it creates all the episodes, how do I add the files to the episodes? I know when adding movies you are give the option to upload the movie, how do I do the same for tv shows?

**Comment by alallier** [comment]
Update: Figured out you had to drag and drop in the browser to upload TV shows, didn't work in linux had to move to windows

**Comment by dularion** [comment]
Didnt work in Linux?  Thats a shame! What Linux distribution did you use? What browser?

**Comment by z3ntu** [comment]
Ubuntu 15.04 Chrome dev it works!

**Comment by alallier** [comment]
Ubuntu 14.04 Chrome and Firefox, on the streama website it shows a browse for file button on each episode was that feature removed?

**Comment by dularion** [comment]
There was a "browse for file" button some time ago, but it didnt make much sense, as it only showed already uploaded files. instead, it will soon be replaced by this feature: https://github.com/dularion/streama/issues/66

**Comment by dularion** [comment]
In the next version I will be adding an improved file-manager. You will still be able to simply drag-and-drop files as usual, but you can also open a more advanced file-manager. This will hopefully help new users find the upload functionality as well as not hinder "power-users". 
 ![http://new.tinygrab.com/d9072ef56482e80b5fb1d96fee1baaedf8629daaf5.png](http://new.tinygrab.com/d9072ef56482e80b5fb1d96fee1baaedf8629daaf5.png)

**Comment by alallier** [comment]
Okay looks great

**Comment by stramel** [comment]
@dularion How does streama handle multi-episode files?

**Comment by dularion** [comment]
hmm.. well I guess yes, since its all in one video file, you would simply create an episode record for both. although the episode_number, which is used for sorting etc, would be challenging for you to adjust correctly. Easiest would probably to see what the api does when you fetch all episode for a season. If it is an official double-episode, I am actually not sure how the api returns those values. But they probably got some way, and we could try mimicking that. Can you give me an example? What show/season/episode would be such a case?

**Comment by stramel** [comment]
The closest one I can think of off the top of my head would be Avatar: The Last Airbender. The first 2 episodes aired back to back and there are next to no files where they are split apart. However, tvDB, shows them as two separate episodes.

@admwx7 might be able to think of some others.
