### ISSUE TITLE
JAVA_HOME enviorment variable not set

### ISSUE THREAD

**Issue by the4ndy** [dularion/streama#95]
i get the following error when trying to install Streama on a fresh Ubuntu 14.04 VM

$ sudo ./grailsw war ROOT.war -Dgrails.env=production
grailsw: JAVA_HOME environment variable is not set

**Comment by z3ntu** [comment]
you have to set the JAVA_HOME environment variable...

**Comment by the4ndy** [comment]
Ok I get that, I assumed that that process would be done as a part of the Java install, however if it isnt, and is a requirement for this software to be installed or work, it would be nice to include it in the instructions or maybe just help me out and point me in the right direction. I have attempted at least 3 tutorials in regards to the JAVA_HOME variable in my path and none work and I do not understand due to my own lack of experience and knowledge as well as a lack of instruction as to how to resolve this. :(

**Comment by admwx7** [comment]
This instructions don't belong in this repo, we shouldn't be responsible
for accounting for flaws in other software.

Easiest thing is to fully uninstall java then reinstall, that should run
the script to add it to your path again, hopefully it won't fail a second
time.

**Comment by the4ndy** [comment]
Ok, I understand there is debate over if those instructions should be in your instructions....if its needed to be known to make your software work, it might be worth mentioning.....however, I will do what your suggest, uninstall and re-install Java.....can you be more specific though when you mention Java....is it the JDK, the javac, java, there are like many many java packages on my server. And i do not know where the problem could have arrised, I have tried from a fresh Ubunutu 14.04 image on multiple occasions and follow the instructions to the letter... :( I just dont know what i am doing wrong other than being given some incomplete instructions, which is fine, if you dont have the time or effort to be walking the noobs like me through install then so be it, but maybe i warning or a hey, you need to do this on your own, message.

**Comment by jdollar** [comment]
@the4ndy The java version you need would be the jdk.

For a quick overview you'll need to install a jdk (openjdk should be fine) then locate the installation directory. On my arch, debian and centos machine it is located at /usr/lib/jvm/<INSTALLED JDK> where <INSTALLED JDK> would be the jdk you just installed with apt-get install.

afterwards you'll want to add this line to your .bashrc:

```
export JAVA_HOME=/usr/lib/jvm/<INSTALLED JDK>
```

Then to ensure those changes are populated to your current session:
```
. bashrc
```

That should be all you need to setup the JAVA_HOME on your ubuntu machine. You can also check out the wiki for this project on the Centos setup. It has a section similar to the above for installing the JAVA_HOME and it should translate over to ubuntu sans issues.

I believe the default JAVA_HOME is only setup for Mac OSX (darwin machines) and cygwin. I don't believe the default gradle wrapper takes into account other versions. I'm not 100% sure if it would be possible to change that. Since it changes with the gradle versions it might not make sense to make any changes to that file.

PS:
I checked out the script in the wiki about the ubuntu install and the installed jdk location is: /usr/lib/jvm/jdk1.7.0_65/. You should be able set the following in your .bashrc in order to set your JAVA_HOME if you still used that script:

```
export JAVA_HOME=/usr/lib/jvm/jdk1.7.0_65/
```
Then just reload the .bashrc.

**Comment by the4ndy** [comment]
You sir are a gentleman and a scholar. You have helped me greatly and I am indebted to you. I have resolved the JAVA_HOME issue and was able to successfully build my WAR file, i moved it to my remote server and restarted the tomcat7 service, tailed the log file, waited for the "Server startup" line and navigated to localhost:8080..however, i was greeted with a blank page :disappointed: A quick nmap scan of my server shows port 8080 open and the service Tomcat/Coyote running. I have spun up a whole new server and meticulously gone through the steps again, this time being able to resolve the JAVA_HOME issue much easier, but still ending up with the same result....any assistance with this is greatly appreciated. Thanks

**Comment by jdollar** [comment]
I'm glad you were able to resolve the JAVA_HOME issues! :)

For the Issue relating to navigating to the streama instance I just have some general questions:

When generating the war it is in the same fashion as the ubuntu wiki install where it is named ROOT.war placed in the tomcat webapp directory correct? I am guessing since you got the tail of the logs it is, but just to make sure. If it isn't named ROOT.war then localhost:8080 would not work. If it is something like streama.war and placed in the webapp directory it would be localhost:8080/streama for tomcat.

You mention the war is on a remote server, is the remote server the ubuntu machine? Are you trying to access the war that is on the remote machine from your desktop or from that remote machine? I ask because you mention using localhost:8080 to try and access the war, but if the war is on a remote machine then you would have to use the IP address of the machine with the port number. Most likely something like 192.168.XX.XX:8080. 

When you run nmap what ip are you hitting? localhost or the one for the remote server? Do you have a firewall running on the remote server? Iptables or firewalld?

**Comment by jdollar** [comment]
Relates to #96 . Another possible cause of the blank page issue might be the database connection. On the server logs you might see some errors when trying to instantiate the sessionFactory.

The default I believe is to use the root user to connect to the streama database, but normally on a fresh mysql install you don't have the ability to login remotely using root. From the ubuntu machine I would trying logging in to your mysql and checking the mysql databases's user table to see what root users you have:

```
USE DATABASE mysql;
SELECT User, host FROM user WHERE user='root';
```

For remote connections you are looking for a user of root with a host of wildcard (%). If that isn't there you have two options: 

1) Create a remote root user and restart your mysql instance then redeploy the streama application:
```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
```

2) Create a Streama user for the database connection and reconfigure streama and rewar it. The information relating to doing that can be found in the wiki for setting up streama in CentOS under the installing mysql section.

**Comment by jdollar** [comment]
Removed my comment on the database connection, because after thinking about the issue since the database should be on the same ubuntu machine it should be fine just having the root user for localhost. Was thinking the database was on a different machine and thus needed remote access to the root account. Misunderstanding on my part.

The blank page when navigating to the url could still be an issue with your streama instance connecting to the database. Do you have any errors on the server log that states anything relating to errors instantiating the session factory?

**Comment by the4ndy** [comment]
i am performing all of the installation steps on a "remote" server. The server is only remote in that it is an Ubuntu VM on a server on my LAN. This is my local network to which I am the administrator and to be honest there are no interior firewall rules at all (only perimeter to which does not apply cause this is all done on the LAN). I am leaving it named ROOT.war as the instructions mention. the IP of the machine is at 10.0.0.7 in my case and has a statically set IP address. there are no firewall rules configured on the server outside of a standard Ubuntu 14.04 server install (which I believe is none, I have checked the ufw and it is disabled). Also, I have run the nmap from my machine on the LAN as well as from the localhost itself. 

In an effort to avoid mistake in the couple steps it takes to deploy on a server, I have instead tried to use the docker images, and while my experience with Docker is limited, I have followed their instructions on installing their software and have confirmed via the metrics provided by Docker that my installation was successful and with no errors. I then install Tomcat and mysql-server (apt-get install tomcat7 msql-server) and i leave the root password blank. I then run the single docker command modified with root as the user and blank as the password (i have tried it with the defaults, and with the root password as "password" without quotes and even tried making a user "streama" with password "password"). I also have to add an additional tack "-" on to the -name="stream" flag or else docker throws up errors. Ultimately, the end result is near identical, a blank website.

Thanks again for your help!

**Comment by jdollar** [comment]
I'm 99% sure the issue is with the database. I believe there is another issue flying around with the docker image relating to it not correctly creating the database tables so I'm not entirely sure how stable to docker image is at the moment.

In the wiki instructions for ubuntu and centos on the mysql instance you have to create the streama database before anything

```
CREATE DATABASE streama;
```

I haven't seen any information relating to the docker file creating the database, but can you check the mysql server to see if it does indeed have a streama database? Otherwise you might have to create it yourself.

The default log for tomcat is under your tomcat installation/logs/catilina.out. Checking that file to see if there are any errors would be helpful as well.

**Comment by the4ndy** [comment]
I am not an SQL guy, my DB knowledge is limited. However, I can say that I have tried the Docker setup both with creating my own DB and without, both have the same, blank page result. And when I create the DB, I am using the command `mysql> CREATE DATABASE streama;` which is taken straight from the installation instructions on this GitHub Repo. Other than that though I do not do any additional MySQL configuration (I am under the assumption that if it was needed it would be stated).

I will cease trying the Docker builds for now and will give the remote installation another couple of trys. I will thoroughly examine the output of the catalina.out file and will post anything I find that may be the problem (or perhaps Ill share the whole output, it may be easier).

Thanks again for the help.

**Comment by the4ndy** [comment]
just did another fresh setup and documented my process thoroughly. In the end I got a pretty bad looking error in the log that is requested to be tailed. 
I have pasted the errors here: http://pastebin.com/SG3BqMLW
and my step by step here: http://pastebin.com/Ubr6arnS

Hopefully this can shed some light on my mistake along the way. Again my sincerest thanks for your assistance. It goes much appreciated.

**Comment by jdollar** [comment]
```
  --- lots of dots
  --- it makes a lot of files uglierer
```
Made me chuckle a little. :)


Regarding the error, the relevant section from the catalina.out is:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'streama'
```

I know your steps included:
```
- run mysql> CREATE DATABASE streama;
```
but to double check if the database was created I would try logging into mysql and run the following to see if indeed the database was created:

```
SHOW DATABASES;
```

If it was it should show the database streama in the results. Otherwise try rerunning your create database command while logged into mysql again. It shouldn't be an issue with the username/password for the mysql as it would normally detail that in the output. It just sounds like the database isn't there.

**Comment by the4ndy** [comment]
oh shit! it was the database, like you said, it wasnt there, and i am an idiot when it comes to databases

the trick was that you need to log in the mysql as the root user first
mysql -u root -p
it will prompt for password, in my case it was blank, so enter and move on
then you get the mysql> prompt
from that prompt then type CREATE DATABASE streama;
then SHOW DATABASES; for good measures
pat yourself on the back and feel like a DB admin

now start tomcat and #BOOM it works!

I intend to do a nice write up on getting this working, a supplement to the current install guide, a noob edition i guess you might call it....but I thought maybe I could just ask you guys if there is a proper way to incorporate more detail into the current instructions. I am not a github master, some direction on how to help out would be awesome.....and also, if there is a way I can get a "pull request" out it that would help me as I am working towards the Digital Ocean Hacktoberfest and need to get a number of those (https://www.digitalocean.com/company/blog/hacktoberfest-is-back/), if not, i still want to try and add some of the findings and information I discovered / was taught along the way into the instructions or documents of this project so that it can help others in the future. This project is AWESOME by the way. Thanks again!

**Comment by jdollar** [comment]
Very awesome to hear that the issue is resolved!

Someone else might have more to say on the documentation and where to incorporate details, but I would think now that you have gone through the steps and documented it fairly well it looks like you should have the best ideas of where the current process slipped you up. Out of anyone I would imagine you would have the best point of view on what you think the instructions might be lacking and any additions you feel necessary I am sure would help the documentation.

For the pull request I believe there are a few issues/enhancements on the project that might be worth tackling for the hacktoberfest (After seeing the link you shared I just signed up myself. I like a free shirt!). Might be able to find something there to contribute. Also I'm not entirely sure how active it is, but on the readme there is a badge for the glitter chat for this project. Someone more knowledgeable than I might be there to talk more about the project, its status and where help might be needed.

**Comment by dularion** [comment]
Sorry for the late reply: I would love to enhance the documentation to include any slip-ups that users might have! I believe that this project and it's documentation should guide the user through the setup as good as possible. Thank you for your patience with the setup and thanks to everyone who helped with the issue! I will try to find the time to include this issue in the documentation, or you could do a pull request and include it that way (does that work with the wiki-pages?).
